name: Zero-Touch Production Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute Remote SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          bash /home/ubuntu/automation/backup.sh
          cd /var/www/html
          sudo git pull origin main
          sudo wp search-replace 'http://old-dev-ip' 'https://kiramira.duckdns.org' --allow-root --path=/var/www/html
